spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DB
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: validate
#  security:
#    user:
#      name: admin
#      password: 12345
server:
  servlet:
    context-path: /api
#springdoc:
#  api-docs:
#    enabled: true
