spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DB
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
#  security:
#    user:
#      name: admin
#      password: 12345
server:
  servlet:
    context-path: /api

jwt:
  secret-key: RlgxVlRSVklpTENKU1QweEZYMEZFVFVsT0lsMHNJbUZqWTI5MWJuUk9iMjVGZUhCcGNtVmtJanAwYw==
#  api-docs:
#    enabled: true
